Portal/website/companies/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
#from companies import views as core_views
from rest_framework.urlpatterns import format_suffix_patterns

app_name='companies'
urlpatterns = [
url(r'^index/$',views.index,name='index'),
url(r'^post/new/$', views.transport_new, name='post_new'),
url(r'^detail/(?P<album_id>[0-9]+)/$', views.StockList1.as_view(), name='detail'),
url(r'^albdetail/(?P<album_id>[0-9]+)/$', views.albdetail, name='albdetail'),
url(r'^test/$', views.test, name='test'),
url(r'^service/$', views.service, name='service'),
url(r'^team/$', views.team, name='team'),
url(r'^problems/$', views.problems, name='problems'),
url(r'^contact/$', views.contact, name='contact'),
url(r'^login/$', views.login, name='login'),
url(r'^rregister/$', views.rregister, name='rregister'),
url(r'^register/$', views.register, name='register'),
url(r'^login1/$', views.Login1copy.as_view(), name='login1_new'),
url(r'^loginc/$', views.Logincopy.as_view(), name='loginc_new'),
url(r'^email_verify/(?P<emailto>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/',views.email_verify, name='email_verify'),
url(r'^deid/$', views.StockList0.as_view(), name='deid'),
url(r'^$',views.home, name='home'),
url(r'^login2/$', auth_views.login, {'template_name': 'companies/login.html'}, name='login2'),
url(r'^logout/$', auth_views.logout, {'next_page': 'companies:login2'}, name='logout'),
url(r'^signup/$', views.signup, name='signup'),
url(r'^display/(?P<getPid>\d+)/$',views.display,name='display'),
url(r'^delete/(?P<getPid>\d+)/$', views.deleteProblem, name='deleteProblem'),
url(r'^update/$', views.updateStatus, name='update'),
url(r'^ser/$',views.ProbList.as_view()),
]

Portal/website/website/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views

urlpatterns = [
url(r'^companies/', include('companies.urls')),
    url(r'^admin/', admin.site.urls),
url(r'^stocks/',views.StockList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Portal/website/companies/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Stock1(models.Model):
    data=models.TextField(
        db_column='data',
        blank=True)
    desc= models.TextField(blank=True)
    lati=models.TextField(blank=True)
    long=models.TextField(blank=True)
    email1=models.TextField(blank=True)
    status = models.IntegerField(default = 0,blank=True)
    priority=models.IntegerField(default=0,blank=True)
    def __str__(self):
        return self.desc

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    #phone_= models.CharField(max_length=10, null=False, blank=False)
    adhar_no=models.IntegerField( null=False, blank=False)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

class Useer(models.Model):
	user1=models.CharField(max_length=15)
	pass1=models.CharField(max_length=15)
	email1=models.CharField(max_length=20)
	Adhar=models.CharField(max_length=14,default = '1234-5678-9012')

class Dummy(models.Model):
	duser1=models.CharField(max_length=15)
	bf=models.IntegerField(default=0)
	def __str__(self):
		return self.duser1

Portal/website/companies/forms.py
from django import forms
from .models import Stock1
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib.auth.forms import UserCreationForm
class StockForm(forms.ModelForm):
  class Meta:

      model=Stock1
      fields=['data','desc','lati','long','email1']


#class UserForm(forms.ModelForm):
 #   password = forms.CharField(widget=forms.PasswordInput)

  ##     model = User
    #    fields = ('username', 'email', 'password')
        # labels = {
        #     'username': 'Unique service no',

        # }

###
   #   model=User
    #  fields=['email','password']

#class UserProfileForm(forms.ModelForm):
 #   # phone_no = forms.CharField(widget=forms.)         need to complete it

  ###    fields = ('adhar_no',)


class NewForm(UserCreationForm):
    deptid = forms.IntegerField(required=True)

    class Meta:
        model = User
        fields = ("username", "deptid", "password1", "password2")

    def save(self, commit=True):
        user = super(NewForm, self).save(commit=False)
        user.deptid = self.cleaned_data["deptid"]
        if commit:
            user.save()
        return user

Portal/website/companies/views.py
from django.shortcuts import render
from time import localtime
# Create your views here.
from rest_framework.views import APIView
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from rest_framework import status
from .models import Stock1,Useer,Dummy
from .serializers import StockSerializer ,  StockSerializer1 ,ProbSerializer
from django.views import generic
from django.views.generic.edit  import CreateView
from django.views.generic import  View
from .forms import StockForm
from django.http import  request
from django.http import HttpResponseRedirect,HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.contrib import messages
#Lists all stocks or create a new onedef transport_new(request):
   ##return render(request,'music/transport_edit.html',{'form':form})
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate
from .forms import NewForm
from django.shortcuts import render, redirect

@csrf_exempt
def transport_new(request):
    if request.method == "POST":
        print "hello"
        form = StockForm(request.POST)
        if form.is_valid():
            print "hello"
        #    instance = Transport(file_field=request.FILES['logo'])
         #   instance.save()
            Transport1 = form.save()
            Transport1.save()
            email1=str(request.POST['email1'])
            c1 = Stock1.objects.last()
            c=localtime()
            li=[]
            li.append(str(email1))
            li.append('ramuklinus369@gmail.com')
            send_mail('Thanks for Reporting the problem',
                    'Dear'+''+','+'\n'+'Your Problem token no. is'+' '+'PGAS'+str(c.tm_mday)+str(c.tm_mon)+str(c.tm_year)+str(c1.pk) +'\n'+'Sent From Admin of PGAS System',
                    'ramuklinus369@gmail.com',
                    li)

            return redirect('companies:index')
    else:
        form = StockForm()
    return render(request, 'companies/transport_edit.html', {'form': form})
@csrf_exempt
def index(request):
    all_albums = Stock1.objects.all()
    albums = {'s1':[],'s2':[],'s3':[]}
    for x in xrange(0,all_albums.count()):
        if  x % 3 == 0:
            albums['s1'].append(all_albums[x])
        elif  x % 3 == 1:
            albums['s2'].append(all_albums[x])
        else:
            albums['s3'].append(all_albums[x])

    return render(request, 'companies/index.html',{'albums':albums})

def albdetail(request, album_id):
    album =Stock1.objects.get(pk=album_id)

    return render(request, 'companies/imgdetail.html', {'album': album})

def test(request):
    return render(request,'companies/test.html')
def service(request):
    return render(request,'companies/service.html')
def team(request):
    return render(request,'companies/team.html')
def login(request):
    return render(request,'companies/newLogin.html')
@csrf_exempt
def register(request):
        if request.method=="POST":
            reg=Useer()
            l=Useer.objects.filter(email1=str(request.POST['email']))
            if len(l)>=1:
                redirect('companies:rregister')

            else :
                reg.user1=str(request.POST['first_name'])
                reg.pass1=str(request.POST['password'])
                reg.email1=str(request.POST['email'])
                reg.Adhar=str(request.POST['adhar_no'])
                reg.save()
                return redirect('companies:index')
        return render(request,'companies/newRegister.html')



def rregister(request):
    messages.success(request, 'Sorry, already registered')
    return render(request,'companies/newRegister.html',{'error': 'Already Registerd'})

def problems(request):
    all_albums = Stock1.objects.all()
    albums = {'s1':[],'s2':[],'s3':[]}
    for x in xrange(0,all_albums.count()):
        if  x % 3 == 0:
            albums['s1'].append(all_albums[x])
        elif  x % 3 == 1:
            albums['s2'].append(all_albums[x])
        else:
            albums['s3'].append(all_albums[x])

    return render(request,'companies/problems.html',{'albums':albums})
def contact(request):
    if request.method=="POST":
        li=[]
        li.append(str(request.POST['email']))
        li.append('ramuklinus369@gmail.com')
        try:
            spe=send_mail('From'+' '+str(request.POST['name'])+' '+'About'+' ' +str(request.POST['subject']),request.POST['message'],'ramuklinus369@gmail.com',li)
            return redirect('companies:test')
        except:
            return HttpResponse("Could not process your Request")
    else:
        # messages.success(request,'Send Mail Succesfullu')
        return render(request,'companies/contact.html')

def email_verify(request,emailto):
    l=Dummy.objects.all()
    flag=0
    for i in range(len(l)):
        if str(emailto) == str(l[i]):
            flag=2
            album1=Dummy.objects.get(pk=l[i].id)
            if album1.bf==0:
                album1.delete()
                formreq = Dummy()
                formreq.duser1=str(emailto)
                formreq.bf=1
                formreq.save()
                flag=1
                break
    if flag==1:
        return  HttpResponse("Email verification done")
    if flag==0:
        return  HttpResponse("Not Registered yet")
    if flag==2:
        return  HttpResponse("Already Registered")

class StockList0(APIView):
    def get(self,request):
        stocks=Stock1.objects.all()
        print stocks
        serializer=StockSerializer1(stocks,many=True)
        content = {'user_details': serializer.data}
        return Response(content)
    def post(self):
        pass




class StockList(APIView):
    def get(self,request):
        stocks=Stock1.objects.all()
        serializer=StockSerializer(stocks,many=True)
        content = {'user_count': serializer.data}
        return Response(content)
    def post(self):
        pass
class StockList1(APIView):
    def get(self,request,album_id):
        stocks=Stock1.objects.get(id=album_id)
        serializer=StockSerializer(stocks)
        ls=[]
        #s.append(serializer.data)
        m=serializer.data

        k=str(m['data'])
        m=k.replace("\n","")
        m=m.replace('\r','')
        #ls.append(k)
        #ls.append(type(k))
        return Response(m)
        #content = {'user_count': ls}
        #return Response(content)
    def post(self):
        pass

class Login1(APIView):
    def post(self,request):
        reg=Useer()
        l=Useer.objects.filter(email1=str(request.POST['email']))

        if len(l)>=1:
           n=1
           k=[{"error":"false","dup":n}]
           return Response(k)
        else :
            reg.user1=="none"
            reg.pass1=str(request.POST['password'])
            reg.email1=str(request.POST['email'])
            reg.Adhar="none"
            reg.save()
            k=[{"error":"false","dup":0}]
            return Response(k)

    def get(self,request):
        form = LoginForm()
        return render(request, 'companies/login_new.html', {'form': form})

class Login1copy(APIView):
    def post(self,request):
        reg=Useer()
        l=Useer.objects.filter(email1=str(request.POST['email']))

        if len(l)>=1:
           n=1
           k=[{"error":"false","dup":n}]
           return Response(k)
        else :
            reg.user1=="none"
            reg.pass1=str(request.POST['password'])
            reg.email1=str(request.POST['email'])
            reg.Adhar="none"
            reg.save()
            email1=str(request.POST['email'])
            formreq = Dummy()
            formreq.duser1=str(email1)
            formreq.bf=0
            formreq.save()
            li=[]
            li.append(str(email1))
            li.append('ramuklinus369@gmail.com')
            str1='http://ramuk369.pythonanywhere.com/companies/email_verify/'+str(email1)
            spe=send_mail('From sunil',str1,'ramuklinus369@gmail.com',li)
            k=[{"error":"false","dup":0}]
            return Response(k)

    def get(self,request):
        form = LoginForm()
        return render(request, 'companies/login_new.html', {'form': form})


class Loginc(APIView):
    def post(self,request):
        reg=Useer()
        l=Useer.objects.filter(email1=str(request.POST['email']),pass1=str(request.POST['password']))

        if len(l)>=1:
           k=[{"error":1}]
           return Response(k)
        else :
            k=[{"error":0}]
            return Response(k)

    def get(self,request):
        form = LoginForm()
        return render(request, 'companies/login_new.html', {'form': form})

class Logincopy(APIView):
    def post(self,request):
        reg=Useer()
        email2=str(request.POST['email'])
        l=Useer.objects.filter(email1=str(request.POST['email']),pass1=str(request.POST['password']))
        flag=0
        l2=Dummy.objects.all()
        for i in range(len(l2)):
            if email2 == str(l2[i]):
                album1=Dummy.objects.get(pk=l2[i].id)
                if album1.bf==1:
                    flag=1
                    break
        if len(l)>=1 and flag==1:
            k=[{"error":1}]
            return Response(k)
        else:
            k=[{"error":0}]
            return Response(k)
    def get(self,request):
        form = LoginForm()
        return render(request, 'companies/login_new.html', {'form': form})

@login_required
def home(request):
    Problem1 = Stock1.objects.all()
    return render(request,'companies/try1.html',{'Problem': Problem1})
     #return  HttpResponse("Suceesfully logined")

def signup(request):
    if request.method == 'POST':
        form = NewForm(request.POST)
        if form.is_valid():
            form.save()
            username= form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

Portal/website/companies/templates/companies/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'companies:logout' %}">logout</a>
      {% else %}
        <a href="{% url 'companies:login2' %}">login</a> / <a href="{% url 'companies:signup' %}">signup</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

Portal/website/companies/templates/companies/display.html
{% block content %}
  <h2>Welcome, Mr.{{ user.username }}!</h2>


{% if user.is_authenticated %}
  <a href="{% url 'companies:logout' %}">logout</a>
  {% endif %}
{% endblock %}

{% block body %}<br>
Image: <img src="data:image/jpeg;base64,{{Problem.data}}" alt="" width="200px" height="200px" /><br>
<h1>Description:  {{Problem.desc}}</h1>
  <h2>Status:   {{Problem.status}}</h2>
  <h3>Priority: {{Problem.priority}} </h3>
{% endblock %}

Portal/website/companies/templates/companies/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">
            {{field.errors}}
        </span>
    </div>
        <label class="control-label col-sm-2">
            {{field.label_tag}}
        </label>
    <div class="col-sm-10">
        {{ field }}
    </div>

</div>

{% endfor %}
<label>
   <div class="col-sm-10">

    </div>

</label>

Portal/website/companies/templates/companies/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome, Mr.{{ user.username }}!</h2>

{% endblock %}

Portal/website/companies/templates/companies/imgdetail.html
<html>
<body style="background-color:#ccffff;">
<h1 style="color:green;"><center>Public Grievance</center></h1>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="albums-container container-fluid">
    <div class="row">

        	<div class="col-sm-10 col-lg-4">
            	<div class="thumbnail">
                	<a href="#">
                  		<img src="data:image/jpeg;base64,{{album.data}}" style="width:1000px;height:400px;" class="img-responsive">
                	</a>
                	<div class="caption">
                    	<h2>{{ album.desc}}</h2>
                	</div>
            	 </div>
        	</div>

    </div>
</div>
</body>
</html>

Portal/website/companies/templates/companies/login.html
{% extends 'companies/base.html' %}

{% block content %}
  <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'companies:signup' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

Portal/website/companies/templates/companies/login_new.html
{% block title %} Enroll {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
               <h3>Create a New Account</h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                     {% endif %}
                    <form class="form-horizontal"  role="form" action="" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                    {% include 'companies/form-template.html' %}

                     <div class="form-group">
                         <div class="col-sm-offset-2 col-sm-10">
                             <button type="submit" class="btn btn-success">
                                 Submit
                             </button>
                         </div>
                     </div>
                    </form>
            </div>

        </div>

    </div>

</div>
    {% endblock %}

Portal/website/companies/templates/companies/problems.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
		<!-- BASICS -->
        <meta charset="utf-8">
		<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> -->
        <title>{% block title %}PGAS{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" type="text/css" href="{% static 'PG/css/isotope.css' %}" media="screen" />
		<link rel="stylesheet" href="{% static 'PG/js/fancybox/jquery.fancybox.css' %}" type="text/css" media="screen" />
		<link rel="stylesheet" href="{% static 'PG/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'PG/css/bootstrap-theme.css' %}">
		<link href="{% static 'PG/css/responsive-slider.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'PG/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'PG/css/style.css' %}">

		<link rel="stylesheet" href="{% static 'PG/css/font-awesome.min.css' %}">
		<!-- skin -->
		<link rel="stylesheet" href="{% static 'PG/skin/default.css' %}">
    </head>
{% block body %}
    <body>

	<div class="header">
	<section id="header" class="appear">
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation" data-300="line-height:60px; height:60px; background-color:rgba(0,0,0,1);">
		<!-- <div class="navbar navbar-fixed-top" > -->

				<div class="navbar-header" >
					<h1><a class="navbar-brand" href="#" >Public Grievance Addressal System
					</a></h1>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav" >

					   <li><a href="{% url 'companies:register' %} " target="_blank">Register</a></a></li>
					    <li><a href="{% url 'companies:login' %}" target="_blank">Login</a></a></li>
						<li><a href="{% url 'companies:test' %}">Home</a></li>
            <li class="active"><a href="{% url 'companies:problems' %}">Reported Problems</a></li>
						<!-- <li><a href="#section-about">About</a></li> -->
						<li><a href="{% url 'companies:service' %}">Service</a></li>
						<li><a href="{% url 'companies:team' %}">Team</a></li>
						<li><a href="{% url 'companies:contact' %}">Contact</a></li>
					</ul>
				</div><!--/.navbar-collapse -->

</nav>

	</section>
	</div>

 <section id="section-problems" class="section appear clearfix">
            <div class="container">


                <div class="row mar-bot40">
                    <div class="col-md-offset-3 col-md-6">
                        <div class="section-header">
                            <h2 class="section-heading animated" data-animation="bounceInUp">Reported Problems</h2>
                        </div>
                    </div>
                </div>

                        <div class="row">
                          <div class="col-md-12">
                            <div class="row">
                              <div class="portfolio-items isotopeWrapper clearfix" id="3">

                             {% for album in albums.s1 %}
                                <article class="col-md-4 isotopeItem webdesign">
                                    <div class="portfolio-item">
                                    <div class="wow rotateInUpLeft" data-animation-delay="4.8s">
                                        <img src="data:image/jpeg;base64,{{album.data}}" alt="welcome" width="200px" height="200px" />
                                    </div>
                                         <div class="portfolio-desc align-center">
                                            <div class="folio-info">
                                                <h5><a href="#">{{album.desc}}</a></h5>


                                                     {% if album.email1 %}
                                                     <h5><a href="#">USER: {{album.email1}}</a></h5>
                                                     {% endif %}
                                              <a href="{% url 'companies:albdetail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                             </div>
                                         </div>
                                    </div>
                                </article>
        {% endfor %}
                                        {% for album in albums.s2 %}
                                <article class="col-md-4 isotopeItem photography">
                                    <div class="portfolio-item">
                                    <div class="wow bounceIn">
                                        <img src="data:image/jpeg;base64,{{album.data}}" alt="" width="200px" height="200px" />
                                    </div>
                                         <div class="portfolio-desc align-center">
                                            <div class="folio-info">
                                                <h5><a href="#">{{album.desc}}</a></h5>


                                                     {% if album.email1 %}
                                                     <h5><a href="#">USER: {{album.email1}}</a></h5>
                                                     {% endif %}
                                               <a href="{% url 'companies:albdetail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                             </div>
                                         </div>
                                    </div>
                                </article>
                                 {% endfor %}
 {% for album in albums.s3 %}
                                <article class="col-md-4 isotopeItem photography">
                                    <div class="portfolio-item">
                                    <div class="wow rotateInDownRight">
                                        <img src="data:image/jpeg;base64,{{album.data}}" alt="" width="200px"  height="200px"/>
                                    </div>
                                         <div class="portfolio-desc align-center">
                                            <div class="folio-info">
                                                <h5><a href="#">{{album.desc}}</a></h5>

                                                     {% if album.email1 %}
                                                     <h5><a href="#">USER: {{album.email1}}</a></h5>
                                                     {% endif %}
                                               <a href="{% url 'companies:albdetail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                             </div>
                                         </div>
                                    </div>
                                </article>
 {% endfor %}

                                </div>

                            </div>


                            </div>
                        </div>

            </div>
        </section>
	<a href="#header" class="scrollup"><i class="fa fa-chevron-up"></i></a>

{% endblock %}
<script src="{% static 'PG/js/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
<script src="{% static 'PG/js/jquery.js' %}"></script>
<script src="{% static 'PG/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'PG/js/bootstrap.min.js' %}"></script>
<script src="{% static 'PG/js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'PG/js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'PG/js/fancybox/jquery.fancybox.pack.js' %}"></script>
<script src="{% static 'PG/js/skrollr.min.js' %}"></script>
<script src="{% static 'PG/js/jquery.scrollTo-1.4.3.1-min.js' %}"></script>
<script src="{% static 'PG/js/jquery.localscroll-1.2.7-min.js' %}"></script>
<script src="{% static 'PG/js/stellar.js' %}"></script>
<script src="{% static 'PG/js/responsive-slider.js' %}"></script>
<script src="{% static 'PG/js/jquery.appear.js' %}"></script>
<script src="{% static 'PG/js/grid.js' %}"></script>
  <script src="{% static 'PG/js/main.js' %}"></script>
  <script src="{% static 'PG/js/wow.min.js' %}"></script>
<script>wow = new WOW({}).init();</script>
  <script src="{% static 'PG/contactform/contactform.js' %}"></script>
</body>
</html>

Portal/website/companies/templates/companies/transport_edit.html
{% block title %} Enroll {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
               <h3>Create a New Account</h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                     {% endif %}
                    <form class="form-horizontal"  role="form" action="" method="post" enctype="multipart/form-data">

                    {% include 'companies/form-template.html' %}

                     <div class="form-group">
                         <div class="col-sm-offset-2 col-sm-10">
                             <button type="submit" class="btn btn-success">
                                 Submit
                             </button>
                         </div>
                     </div>
                    </form>
            </div>

        </div>

    </div>

</div>
    {% endblock %}